### ISSUE TITLE
Feature request: nuget package for MidiSharp

### ISSUE THREAD

**Issue by christophediericx** [stephentoub/MidiSharp#1]
Thank you for sharing this library. For my current use case, this looks like a good foundation to start building upon. Would it be possible to expose a nuget package for the library? Thanks!

**Comment by stephentoub** [comment]
Hey @christophediericx, very sorry for not replying sooner... somehow I missed your request.  I've not invested much in this library for a long time, but if/when I do I'll consider a nuget package for it.

**Comment by christophediericx** [comment]
Hi @stephentoub, no worries, no problem at all. Thanks for taking the time to reply!
