### ISSUE TITLE
Just a Thank You

### ISSUE THREAD

**Issue by tuneis** [stephentoub/MidiSharp#6]
@stephentoub 

I wasn't sure how to email you to thank you for making this library so I will just post it here. I used the library code to create a web app that generates riff's where you can download the midi file and import it into any Digital Audio Workstation (DAW) or Guitar Pro for that matter. It was a fun little project and I wouldn't have been able to accomplish without your code. So thank you.

If you'd like to check it out it's located at: http://tuneis.ddns.net

I put a reference to your repository in the footer.

**Comment by stephentoub** [comment]
Glad it was helpful to you!
